spring:
  application:
    name: gamification-service
  threads:
    virtual:
      enabled: true

server:
  port: ${PORT:8086}

dbarena:
  security:
    jwt:
      secret: ${DBArena_JWT_SECRET:}
  gamification:
    mongo-uri: ${DBArena_GAMIFICATION_MONGO_URI:mongodb://localhost:27017}
    mongo-database: ${DBArena_GAMIFICATION_MONGO_DATABASE:DBArena_gamification}

mongock:
  migration-scan-package:
    - com.DBArena.services.gamification.mongock
  mongo-db:
    uri: ${DBArena_GAMIFICATION_MONGO_URI:mongodb://localhost:27017}
    database: ${DBArena_GAMIFICATION_MONGO_DATABASE:DBArena_gamification}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html
